{
  "toString": "{\n  \"name\": \"coder-house\",\n  \"version\": \"1.0.0\",\n  \"description\": \"\",\n  \"main\": \"ejerciciopractico.js\",\n  \"type\": \"module\",\n  \"dependencies\": {\n    \"abbrev\": \"^1.1.1\",\n    \"anymatch\": \"^3.1.3\",\n    \"balanced-match\": \"^1.0.2\",\n    \"binary-extensions\": \"^2.2.0\",\n    \"brace-expansion\": \"^1.1.11\",\n    \"braces\": \"^3.0.2\",\n    \"chokidar\": \"^3.5.3\",\n    \"concat-map\": \"^0.0.1\",\n    \"debug\": \"^3.2.7\",\n    \"fill-range\": \"^7.0.1\",\n    \"glob-parent\": \"^5.1.2\",\n    \"has-flag\": \"^3.0.0\",\n    \"ignore-by-default\": \"^1.0.1\",\n    \"is-binary-path\": \"^2.1.0\",\n    \"is-extglob\": \"^2.1.1\",\n    \"is-glob\": \"^4.0.3\",\n    \"is-number\": \"^7.0.0\",\n    \"lru-cache\": \"^6.0.0\",\n    \"minimatch\": \"^3.1.2\",\n    \"ms\": \"^2.1.3\",\n    \"nodemon\": \"^3.0.1\",\n    \"nopt\": \"^1.0.10\",\n    \"normalize-path\": \"^3.0.0\",\n    \"picomatch\": \"^2.3.1\",\n    \"pstree.remy\": \"^1.1.8\",\n    \"readdirp\": \"^3.6.0\",\n    \"semver\": \"^7.5.4\",\n    \"simple-update-notifier\": \"^2.0.0\",\n    \"supports-color\": \"^5.5.0\",\n    \"to-regex-range\": \"^5.0.1\",\n    \"touch\": \"^3.1.0\",\n    \"undefsafe\": \"^2.0.5\",\n    \"yallist\": \"^4.0.0\"\n  },\n  \"devDependencies\": {},\n  \"scripts\": {\n    \"test\": \"echo \\\"Error: no test specified\\\" && exit 1\"\n  },\n  \"keywords\": [],\n  \"author\": \"German\",\n  \"license\": \"ISC\"\n}",
  "toObject": {
    "name": "coder-house",
    "version": "1.0.0",
    "description": "",
    "main": "ejerciciopractico.js",
    "type": "module",
    "dependencies": {
      "abbrev": "^1.1.1",
      "anymatch": "^3.1.3",
      "balanced-match": "^1.0.2",
      "binary-extensions": "^2.2.0",
      "brace-expansion": "^1.1.11",
      "braces": "^3.0.2",
      "chokidar": "^3.5.3",
      "concat-map": "^0.0.1",
      "debug": "^3.2.7",
      "fill-range": "^7.0.1",
      "glob-parent": "^5.1.2",
      "has-flag": "^3.0.0",
      "ignore-by-default": "^1.0.1",
      "is-binary-path": "^2.1.0",
      "is-extglob": "^2.1.1",
      "is-glob": "^4.0.3",
      "is-number": "^7.0.0",
      "lru-cache": "^6.0.0",
      "minimatch": "^3.1.2",
      "ms": "^2.1.3",
      "nodemon": "^3.0.1",
      "nopt": "^1.0.10",
      "normalize-path": "^3.0.0",
      "picomatch": "^2.3.1",
      "pstree.remy": "^1.1.8",
      "readdirp": "^3.6.0",
      "semver": "^7.5.4",
      "simple-update-notifier": "^2.0.0",
      "supports-color": "^5.5.0",
      "to-regex-range": "^5.0.1",
      "touch": "^3.1.0",
      "undefsafe": "^2.0.5",
      "yallist": "^4.0.0"
    },
    "devDependencies": {},
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "German",
    "license": "ISC"
  },
  "size": 1232,
  "newProperty": "Nuevo valor"
}
